version: '3.8'
services:
  streamlit:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: ghost-dashboard
    image: nchhstpoddevcontainerregistry.azurecr.io/ghost-dashboard
    restart: unless-stopped

    ports:
      - "8501:8501"

    # Volume mapping 
    volumes:
      - ./mounts/appextensions:/app/mounts/appextensions

      # - ./data:/app/data
      # - ./.logs:/app/.logs

      # - ./mounts/appextensions:/app/data
      # - ./.logs:/app/.logs

    # environment:
    #   - WEBSITE_MOUNT_appextensions=value
 