version: '3.8'
services:
  streamlit:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name:  ${containerName}
    image: ${azContainerRegistry}/${containerName}
    restart: unless-stopped

    ports:
      - "8501:8501"

    # volumes:
    #   - ./data:/app/data
