version: '3.8'
services:
  streamlit:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: ghost-dashboard
    image: nchhstpoddevcontainerregistry.azurecr.io/ghost-dashboard
    restart: unless-stopped

    ports:
      - "8501:8501"

    # volumes:
    #   - ./data:/app/data
